/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EVotingInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "candidates" | "checkInVoter" | "checkedInVoters" | "createElection" | "electionCount" | "elections" | "getCandidate" | "getElection" | "hasVoted" | "owner" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateAdded" | "ElectionCreated" | "VoteCast" | "VoterCheckedIn"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'candidates', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkInVoter', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'checkedInVoters', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createElection', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'electionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'elections', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidate', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getElection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkInVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkedInVoters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'elections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace CandidateAddedEvent {
      export type InputTuple = [electionId: BigNumberish, candidateId: BigNumberish, name: string];
      export type OutputTuple = [electionId: bigint, candidateId: bigint, name: string];
      export interface OutputObject {electionId: bigint, candidateId: bigint, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionCreatedEvent {
      export type InputTuple = [electionId: BigNumberish, title: string, startTime: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [electionId: bigint, title: string, startTime: bigint, endTime: bigint];
      export interface OutputObject {electionId: bigint, title: string, startTime: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [electionId: BigNumberish, candidateId: BigNumberish, voter: AddressLike];
      export type OutputTuple = [electionId: bigint, candidateId: bigint, voter: string];
      export interface OutputObject {electionId: bigint, candidateId: bigint, voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterCheckedInEvent {
      export type InputTuple = [electionId: BigNumberish, voter: AddressLike];
      export type OutputTuple = [electionId: bigint, voter: string];
      export interface OutputObject {electionId: bigint, voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): EVoting;
    waitForDeployment(): Promise<this>;

    interface: EVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_electionId: BigNumberish, _name: string, ],
      [void],
      'nonpayable'
    >
    

    
    candidates: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, string, bigint] & {id: bigint, name: string, voteCount: bigint }],
      'view'
    >
    

    
    checkInVoter: TypedContractMethod<
      [_electionId: BigNumberish, _voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    checkedInVoters: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createElection: TypedContractMethod<
      [_title: string, _startTime: BigNumberish, _endTime: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    electionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    elections: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, boolean, bigint] & {id: bigint, title: string, startTime: bigint, endTime: bigint, exists: boolean, candidateCount: bigint }],
      'view'
    >
    

    
    getCandidate: TypedContractMethod<
      [_electionId: BigNumberish, _candidateId: BigNumberish, ],
      [[bigint, string, bigint] & {id: bigint, name: string, voteCount: bigint }],
      'view'
    >
    

    
    getElection: TypedContractMethod<
      [_electionId: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint] & {id: bigint, title: string, startTime: bigint, endTime: bigint, candidateCount: bigint }],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [_electionId: BigNumberish, _candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_electionId: BigNumberish, _name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, string, bigint] & {id: bigint, name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'checkInVoter'): TypedContractMethod<
      [_electionId: BigNumberish, _voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkedInVoters'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createElection'): TypedContractMethod<
      [_title: string, _startTime: BigNumberish, _endTime: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'electionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'elections'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, boolean, bigint] & {id: bigint, title: string, startTime: bigint, endTime: bigint, exists: boolean, candidateCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidate'): TypedContractMethod<
      [_electionId: BigNumberish, _candidateId: BigNumberish, ],
      [[bigint, string, bigint] & {id: bigint, name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getElection'): TypedContractMethod<
      [_electionId: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint] & {id: bigint, title: string, startTime: bigint, endTime: bigint, candidateCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_electionId: BigNumberish, _candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'ElectionCreated'): TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'VoterCheckedIn'): TypedContractEvent<VoterCheckedInEvent.InputTuple, VoterCheckedInEvent.OutputTuple, VoterCheckedInEvent.OutputObject>;

    filters: {
      
      'CandidateAdded(uint256,uint256,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'ElectionCreated(uint256,string,uint256,uint256)': TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
      ElectionCreated: TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
    

      'VoteCast(uint256,uint256,address)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'VoterCheckedIn(uint256,address)': TypedContractEvent<VoterCheckedInEvent.InputTuple, VoterCheckedInEvent.OutputTuple, VoterCheckedInEvent.OutputObject>;
      VoterCheckedIn: TypedContractEvent<VoterCheckedInEvent.InputTuple, VoterCheckedInEvent.OutputTuple, VoterCheckedInEvent.OutputObject>;
    
    };
  }