/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EVoting } from './EVoting.js';
export * as factories from './factories/index.js';
export { EVoting__factory } from './factories/EVoting__factory.js';